package net.nekomura.dcbot.Enums

enum class ConfigLongData {
    OWNER,
    SCHEDULED_CHECKER_DELAY,
    CHECK_PIXIV_UPDATE_DELAY,
    CHECK_MINECRAFT_UPDATE_DELAY,
    MINECRAFT_PUSH_NOTIFICATION_CHANNEL,
    PIXIV_PUSH_NOTIFICATION_CHANNEL,
    PIXIV_R18_PUSH_NOTIFICATION_CHANNEL
}